### ISSUE TITLE
Unable to Install luci-app-samba4

### ISSUE THREAD

**Issue by srimo01** [thaneb/TL-MR3020-OpenWRT-Extroot-Ready#1]
Thanks for your work on packaging this firmware. I'm able to install this successfully on my MR3020 and install luci. However when proceeding to install samba, it fails with below error. Please fix this

```
root@OpenWrt:~# opkg update
Downloading http://73connection.com/openwrt/targets/ar71xx/tiny/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading http://73connection.com/openwrt/targets/ar71xx/tiny/packages/Packages.sig
Signature check passed.
root@OpenWrt:~# opkg install luci-app-samba4
Unknown package 'luci-app-samba4'.
Collected errors:
 * opkg_install_cmd: Cannot install package luci-app-samba4.

```

**Comment by srimo01** [comment]
> Thanks for your work on packaging this firmware. I'm able to install this successfully on my MR3020 and install luci. However when proceeding to install samba, it fails with below error. Please fix this
> 
> ```
> root@OpenWrt:~# opkg update
> Downloading http://73connection.com/openwrt/targets/ar71xx/tiny/packages/Packages.gz
> Updated list of available packages in /var/opkg-lists/openwrt_core
> Downloading http://73connection.com/openwrt/targets/ar71xx/tiny/packages/Packages.sig
> Signature check passed.
> root@OpenWrt:~# opkg install luci-app-samba4
> Unknown package 'luci-app-samba4'.
> Collected errors:
>  * opkg_install_cmd: Cannot install package luci-app-samba4.
> ```

I copied luci-app-samba4 along with all dependency to /tmp/tmp in order to attempt a manual install and ran into a installation failure related to dbus (see console output below)

attr_2.4.48-1_mips_24kc.ipk
avahi-dbus-daemon_0.8-1_mips_24kc.ipk
dbus_1.12.12-1_mips_24kc.ipk
libattr_2.4.48-1_mips_24kc.ipk
libavahi-client_0.8-1_mips_24kc.ipk
libavahi-dbus-support_0.8-1_mips_24kc.ipk
libcap_2.27-1_mips_24kc.ipk
libdaemon_0.14-5_mips_24kc.ipk
libdbus_1.12.12-1_mips_24kc.ipk
libexpat_2.2.9-1_mips_24kc.ipk
libgcc1_7.5.0-2_mips_24kc.ipk
libgmp10_6.1.2-2_mips_24kc.ipk
libgnutls_3.6.13-1_mips_24kc.ipk
libncurses6_6.1-5_mips_24kc.ipk
libnettle7_3.5.1-1_mips_24kc.ipk
libopenssl1.1_1.1.1g-1_mips_24kc.ipk
libpopt0_1.16-2_mips_24kc.ipk
libpthread_1.1.24-2_mips_24kc.ipk
libreadline8_8.0-1_mips_24kc.ipk
libtasn1_4.15.0-1_mips_24kc.ipk
libtirpc_1.2.5-1_mips_24kc.ipk
luci-app-samba4_git-20.142.51595-0c6fd62-1_all.ipk
samba4-libs_4.11.6-1_mips_24kc.ipk
samba4-server_4.11.6-1_mips_24kc.ipk
terminfo_6.1-5_mips_24kc.ipk
zlib_1.2.11-3_mips_24kc.ipk

```
root@OpenWrt:/tmp/tmp# opkg install *.ipk
Package attr (2.4.48-1) installed in root is up to date.
Package avahi-dbus-daemon (0.8-1) installed in root is up to date.
Installing dbus (1.12.12-1) to root...
Installing libdbus (1.12.12-1) to root...
Package libattr (2.4.48-1) installed in root is up to date.
Package libavahi-client (0.8-1) installed in root is up to date.
Package libavahi-dbus-support (0.8-1) installed in root is up to date.
Package libcap (2.27-1) installed in root is up to date.
Package libdaemon (0.14-5) installed in root is up to date.
Package libdbus (1.12.12-1) installed in root is up to date.
Package libexpat (2.2.9-1) installed in root is up to date.
Package libgcc1 (7.5.0-2) installed in root is up to date.
Package libgmp10 (6.1.2-2) installed in root is up to date.
Package libgnutls (3.6.13-1) installed in root is up to date.
Package libncurses6 (6.1-5) installed in root is up to date.
Package libnettle7 (3.5.1-1) installed in root is up to date.
Package libopenssl1.1 (1.1.1g-1) installed in root is up to date.
Package libpopt0 (1.16-2) installed in root is up to date.
Package libpthread (1.1.24-2) installed in root is up to date.
Package libreadline8 (8.0-1) installed in root is up to date.
Package libtasn1 (4.15.0-1) installed in root is up to date.
Package libtirpc (1.2.5-1) installed in root is up to date.
Package luci-app-samba4 (git-20.142.51595-0c6fd62-1) installed in root is up to date.
Package samba4-libs (4.11.6-1) installed in root is up to date.
Package samba4-server (4.11.6-1) installed in root is up to date.
Package terminfo (6.1-5) installed in root is up to date.
Package zlib (1.2.11-3) installed in root is up to date.
Configuring libdbus.
Configuring dbus.
dbus[2030]: Unknown group "netdev" in message bus configuration file

```

**Comment by thaneb** [comment]
Glad to see someone play with it too. I start to look what happen, the package is present in its directory, so i start look to re-produce the step to check what happen.
Are you using the extroot ?

**Comment by srimo01** [comment]
Yes, using extroot. Steps to reproduce this Issue would be

1. Flash openwrt-19.07-ar71xx-tiny-tl-mr3020-v1-squashfs-factory.bin on TL-MR3020 v1.x
2. Run /etc/extroot-sda1.sh
3. Run opkg update
4. Run opkg install luci-app-samba4

You should be presented with below error message
```
root@OpenWrt:~# opkg install luci-app-samba4
Unknown package 'luci-app-samba4'.
Collected errors:
 * opkg_install_cmd: Cannot install package luci-app-samba4.

```

**Comment by srimo01** [comment]
> The truth is maybe a simple opkg update could now solve it

Absolutely, i did that and now see the samba4 package in the System --> Software list which was missing before. I did get samba server to install the hard way, i.e. recursive trial and error figuring out each dependency and bulk installing them. I have samba4 functional on TL-MR3020 v1.x (thanks to your hard work)  so this Issue can be closed as resolved.

**Comment by thaneb** [comment]
Glad to know it's now working well.
Don't hesitate to ask me if there's extra packages you may need, my virtual machine dedicated to the openwrt build processing is fast so I should be able to build things easily.
