### ISSUE TITLE
Adding Batman-adv support

### ISSUE THREAD

**Issue by MerGr** [thaneb/TL-MR3020-OpenWRT-Extroot-Ready#6]
Hello, I'm trying to make my MR3020 v1 into a mesh node for my home network, but batman-adv and it's dependencies are missing from the repo, I've tried to manually install batman adv ipks but failed due to incompatible kernel version or missing dependencies, I've managed to install wpad-mesh for 802.11s support, but no luck with batman-adv, can you please add these packages to the repo:
batmand
kmod-batman-adv
luci-app-batman
batctl
and their respective dependencies.
Thank you for the help.

**Comment by thaneb** [comment]
Thank you for trying to use this build for the MR3020.
If I well found batmand, kmod-batman-adv and batctl, luci-app-batman seems unavailable, so you will need to use the CLI to configure BATMAN.
Build done, currently uploading new files.

**Comment by thaneb** [comment]
upload done, enjoy (at your own risk of course ^^)
