### ISSUE TITLE
Package Request : kmod-bonding

### ISSUE THREAD

**Issue by MerGr** [thaneb/TL-MR3020-OpenWRT-Extroot-Ready#8]
Hello, I require kmod-bonding package to enable VPS bonding to join two network connections.

Please compile a version compatible with the kernel, I appreciate the work you do, you brought new life to my MR3020.

**Comment by thaneb** [comment]
Hello and thank you for your message, i won't have any access to my builder until May the 10th, so I'm sorry to say that you will need to wait to know if the build is doable or not. I will update you ASAP.

**Comment by thaneb** [comment]
New build complete with kmod-bonding compiled as kernel module. uploading files now, should be all online in 3 minutes.

**Comment by thaneb** [comment]
upload complete, please confirm if what you trying to do is working or if you need more compilation :)

**Comment by MerGr** [comment]
I've long since abandoned the project because I don't want to risk breaking my ISP's ToS, but I have a new idea to turn it into a Tailscale subnet router, so I'll need tailscale, tailscaled, libustream-openssl and it's dependencies compiled

**Comment by thaneb** [comment]
Sorry, i had a look, unable to find tailscale, and it seems unsupported on this openwrt version 
[https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjl-7ThwYj_AhVHz6ACHfORB9IQFnoECAcQAQ&url=https%3A%2F%2Ftechoverflow.net%2F2022%2F08%2F23%2Fis-tailscale-available-for-openwrt-19-07%2F&usg=AOvVaw1nt4p5lZ4Yspeq89mp7OSH](url)

**Comment by MerGr** [comment]
There are backports to 19.07 available on Github : https://lanrat.github.io/openwrt-tailscale-repo/

(Using this gives me illegal instruction error sadly)
You can also build from source binaries :
https://github.com/adyanth/openwrt-tailscale-enabler
(sadly it fills the RAM even with swap, maybe editing the script to download the files to the extroot might work ?)
